### ISSUE TITLE
Proxy Config Struct

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/bridger#15]
Currently, there is a ```relayer``` key in config which is only used when proxy account is open.

A minor suggestion would be.

- [x] rename relayer to a more accurate name, e.g. ```real```
- [x] adding a ```proxy``` tag to define keys only for proxy
- [x] current seed key have different meanings in two cases, if proxy is closed, it means the private key of relayer, if proxy is opened, it means the private key of proxy account.
- [x] Adding documents explain the config. (@clearloop said that it is auto generated now, but it is not friendly to add docs for it, prefer removing auto generate mechanism)

```
seed = ""

[proxy]
real = ""
```

**Comment by wuminzhe** [comment]
```toml
# darwinia node websocket json-rpc endpoint
node = 'wss://crab.darwinia.network'

# private key of relayer, or, private key of proxy
seed = '//Alice'

# shadow http restful endpoint
shadow = 'https://testnet.shadow.darwinia.network.l2me.com'

# allowing `real` account to give permission to `proxy` account to dispatch calls
[proxy]
# The account (32 bytes) that the proxy will make a call on behalf of
# Set to a zero-length string if there is no proxy need
real = '' 

[eth]
# ethereum json-rpc endpoint
rpc = 'https://ropsten.infura.io/v3/0bfb9acbb13c426097aabb1d81a9d016'
start = 8647036

[eth.contract.ring]
# erc20 contract of ring
address = '0xb52FBE2B925ab79a821b261C82c5Ba0814AAA5e0'
# cross transfer topic
topics = ['0xc9dcda609937876978d7e0aa29857cb187aea06ad9e843fd23fd32108da73f10']

[eth.contract.kton]
# erc20 contract of kton
address = '0x1994100c58753793D52c6f457f189aa3ce9cEe94'
# cross transfer topic
topics = ['0xc9dcda609937876978d7e0aa29857cb187aea06ad9e843fd23fd32108da73f10']

[eth.contract.bank]
# gringotts bank contract
address = '0x6EF538314829EfA8386Fc43386cB13B4e0A67D1e'
# cross transfer topic
topics = ['0xe77bf2fa8a25e63c1e5e29e1b2fcb6586d673931e020c4e3ffede453b830fb12']

[eth.contract.issuing]
# erc20 ring and kton issuing contract
address = '0x49262B932E439271d05634c32978294C7Ea15d0C'
topics = []

[step]
ethereum = 30
relay = 60
redeem = 90
guard = 30
```
