### ISSUE TITLE
Change contracts config from object to array

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/bridger#192]
```
ethereum:
  rpc: https://ropsten.infura.io/v3/xxx
  contract:
    ring:
      address: 0xb52FBE2B925ab79a821b261C82c5Ba0814AAA5e0
      topics:
        - 0xc9dcda609937876978d7e0aa29857cb187aea06ad9e843fd23fd32108da73f10
    kton:
      address: 0x1994100c58753793D52c6f457f189aa3ce9cEe94
      topics:
        - 0xc9dcda609937876978d7e0aa29857cb187aea06ad9e843fd23fd32108da73f10
    bank:
      address: 0x6EF538314829EfA8386Fc43386cB13B4e0A67D1e
      topics:
        - 0xe77bf2fa8a25e63c1e5e29e1b2fcb6586d673931e020c4e3ffede453b830fb12
    issuing:
      address: 0x49262B932E439271d05634c32978294C7Ea15d0C
      topics:
        - 0xc9dcda609937876978d7e0aa29857cb187aea06ad9e843fd23fd32108da73f10
    relay:
      address: 0xD35Bb6F1bc1C84b53E0995c1830454AB7C4147f1
      topics:
        - 0x91d6d149c7e5354d1c671fe15a5a3332c47a38e15e8ac0339b24af3c1090690f
```

=>

```
ethereum:
  rpc: "https://ropsten.infura.io/v3/xxx"
  contracts:
    - name: ring
      address: "0xb52FBE2B925ab79a821b261C82c5Ba0814AAA5e0"
      topics:
        - "0xc9dcda609937876978d7e0aa29857cb187aea06ad9e843fd23fd32108da73f10"
    - name: kton
      address: "0x1994100c58753793D52c6f457f189aa3ce9cEe94"
      topics:
        - "0xc9dcda609937876978d7e0aa29857cb187aea06ad9e843fd23fd32108da73f10"
    - name: bank
      address: "0x6EF538314829EfA8386Fc43386cB13B4e0A67D1e"
      topics:
        - "0xe77bf2fa8a25e63c1e5e29e1b2fcb6586d673931e020c4e3ffede453b830fb12"
    - name: issuing
      address: "0x49262B932E439271d05634c32978294C7Ea15d0C"
      topics: ~
    - name: relay
      address: "0xd374292D512281b56198F0401b149370D680b89F"
      topics:
        - "0x91d6d149c7e5354d1c671fe15a5a3332c47a38e15e8ac0339b24af3c1090690f"
```
